INSERT INTO adoptr.report_reason (description, reason, model_type) VALUES
('La publicación contiene información errónea o deliberadamente falsa.', 'Contenido engañoso o falso', 'PUBLICATION'),
('El animal ya no está disponible o la información es obsoleta.', 'Animal no disponible', 'PUBLICATION'),
('La publicación se utiliza para publicidad o no está relacionada con el propósito del módulo.', 'Spam o contenido irrelevante', 'PUBLICATION'),
('La publicación contiene imágenes, lenguaje o información ofensiva o inapropiada.', 'Contenido inapropiado', 'PUBLICATION'),
('Sospecha de estafa o intento de engañar a los usuarios.', 'Fraude', 'PUBLICATION'),
('La publicación sugiere o muestra signos de maltrato o negligencia animal.', 'Maltrato animal', 'PUBLICATION'),
('El tipo de publicación no corresponde con la categoría seleccionada.', 'Categoría incorrecta', 'PUBLICATION'),
('El usuario tiene un historial de comportamiento abusivo, insultos o acoso.', 'Comportamiento abusivo', 'PROFILE'),
('Sospecha de que el perfil no pertenece a una persona real o está siendo usado de manera malintencionada.', 'Perfil falso', 'PROFILE'),
('El perfil está intentando hacerse pasar por otra persona.', 'Suplantación de identidad', 'PROFILE'),
('El usuario tiene imágenes o descripciones ofensivas o inapropiadas en su perfil.', 'Contenido inapropiado en el perfil', 'PROFILE'),
('El perfil parece estar relacionado con actividades fraudulentas o engañosas.', 'Fraude o actividad sospechosa', 'PROFILE'),
('El usuario está enviando mensajes no deseados o realizando publicaciones repetitivas.', 'Spam', 'PROFILE'),
('El post contiene lenguaje o imágenes que fomentan el odio, racismo, sexismo u otros tipos de discriminación.', 'Contenido ofensivo o de odio', 'POST'),
('El post tiene como objetivo molestar o acosar a otros usuarios.', 'Acoso', 'POST'),
('El post incluye información privada o confidencial sin el consentimiento de las personas involucradas.', 'Violación de privacidad', 'POST'),
('El post es innecesariamente repetitivo o está promoviendo productos o servicios sin relevancia.', 'Spam', 'POST'),
('El post contiene imágenes o descripciones de violencia, crueldad o contenido explícito.', 'Contenido violento o explícito', 'POST'),
('El post difunde información falsa o errónea, como rumores peligrosos o noticias falsas.', 'Desinformación', 'POST');
